"""Add last_scan to Performer

Revision ID: 05c73f35b9ea
Revises: f4f18dda9600
Create Date: 2025-11-25 11:52:26.172374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c73f35b9ea'
down_revision = 'f4f18dda9600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_scan', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.drop_column('last_scan')

    # ### end Alembic commands ###
