"""Remove legacy keywords column

Revision ID: 1e9fb280b36f
Revises: 8cff8a717d68
Create Date: 2025-11-26 16:48:44.096537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9fb280b36f'
down_revision = '8cff8a717d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
