"""Add scheduled_scan_enabled to performer

Revision ID: a35f6bafb942
Revises: efdebc843132
Create Date: 2025-11-26 17:06:33.156420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35f6bafb942'
down_revision = 'efdebc843132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_scan_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.drop_column('scheduled_scan_enabled')

    # ### end Alembic commands ###
