"""Remove legacy filter_enabled column

Revision ID: efdebc843132
Revises: 1e9fb280b36f
Create Date: 2025-11-26 16:50:47.453161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdebc843132'
down_revision = '1e9fb280b36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.drop_column('filter_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter_enabled', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
