"""Add performer keyword lists

Revision ID: f4f18dda9600
Revises: 7ebc69623d21
Create Date: 2025-11-25 11:34:27.768871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f18dda9600'
down_revision = '7ebc69623d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blacklist_keywords', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('whitelist_keywords', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.drop_column('whitelist_keywords')
        batch_op.drop_column('blacklist_keywords')

    # ### end Alembic commands ###
